[package]
name = "mnema-desktop"
version = "0.0.1"
edition = "2024"

[dependencies]
mnema-core = { path = "../core" }
mnema-app = { path = "../app" }
mnema-infra = { path = "../infra" }

serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio = { version = "1.48", features = ["full"] }
time = { workspace = true }
time-tz = "2"
eframe = "0.34.3"
muda = { version = "0.19.3", default-features = false }
raw-window-handle = "0.6.2"

[dev-dependencies]
tempfile = "3"
